const learner =[
        {   
            id: 1,
            photo: 'https://www.pageantparty.co.uk/wp-content/uploads/2014/03/29111.jpg',
            name: 'Nashwan Kurdali',
            position: 'Front-End Developer',
            email: 'nashwankurdali@gmail.com',
            phone: '+32-11-11-11-11',
            location: 'Brussels , Belgium',
            status: 'active',
            Starting_date: '01/08/2022',
        },
        {   
            id: 2,
            photo: 'https://images.freeimages.com/images/premium/previews/3411/34112724-funny-nerd-woman-smiling.jpg',
            name: 'Taguhi Karakashyan',
            position: 'Front-End Developer',
            email: 'taguhikarakashyan@gmail.com',
            phone: '+32-22-22-22-22',
            location: 'Brussels , Belgium',
            status: 'active',
            Starting_date: '25/07/2022',
        },
        {
            id: 3,
            photo: 'https://st.depositphotos.com/1759606/2726/i/950/depositphotos_27266141-stock-photo-surprised-nerd-guy.jpg',
            name: 'Sebastian Herrera',
            position: 'Front-End Developer',
            email: 'Seba@gmail.com',
            phone: '+32-33-33-33-33',
            location: 'Brussels , Belgium',
            status: 'active',
            Starting_date: '01/08/2022',
        },
        {
        id: 4,
        photo: 'https://assets.entrepreneur.com/content/3x2/2000/20190425112608-7-Reasons-Why-Nerds-Rule-The-Business-World.jpeg?crop=1:1',
        name: 'Liban Abdullahi',
        position: 'Back-End Developer',
        email: 'libanabdullahi@gmail.com',
        phone: '+32-44-44-44-44',
        location: 'Brussels , Belgium',
        status: 'not active',
        Starting_date: '01/09/2022',
        },
        {   
            id: 5,
            photo: 'https://www.pageantparty.co.uk/wp-content/uploads/2014/03/29111.jpg',
            name: 'Nashwan Kurdali',
            position: 'Front-End Developer',
            email: 'nashwankurdali@gmail.com',
            phone: '+32-11-11-11-11',
            location: 'Brussels , Belgium',
            status: 'active',
            Starting_date: '01/08/2022',
        },
        {   
            id: 6,
            photo: 'https://images.freeimages.com/images/premium/previews/3411/34112724-funny-nerd-woman-smiling.jpg',
            name: 'Taguhi Karakashyan',
            position: 'Front-End Developer',
            email: 'taguhikarakashyan@gmail.com',
            phone: '+32-22-22-22-22',
            location: 'Brussels , Belgium',
            status: 'active',
            Starting_date: '25/07/2022',
        },
        {
            id: 7,
            photo: 'https://st.depositphotos.com/1759606/2726/i/950/depositphotos_27266141-stock-photo-surprised-nerd-guy.jpg',
            name: 'Sebastian Herrera',
            position: 'Front-End Developer',
            email: 'Seba@gmail.com',
            phone: '+32-33-33-33-33',
            location: 'Brussels , Belgium',
            status: 'active',
            Starting_date: '01/08/2022',
        },
        {
        id: 8,
        photo: 'https://assets.entrepreneur.com/content/3x2/2000/20190425112608-7-Reasons-Why-Nerds-Rule-The-Business-World.jpeg?crop=1:1',
        name: 'Liban Abdullahi',
        position: 'Back-End Developer',
        email: 'libanabdullahi@gmail.com',
        phone: '+32-44-44-44-44',
        location: 'Brussels , Belgium',
        status: 'not active',
        Starting_date: '01/09/2022',
        },
    ]


export default learner;