const PromoLearnerData =[
    {   
        id: 1,
        photo: 'https://ilarge.lisimg.com/image/7638651/740full-joana-person.jpg',
        name: 'Sabrine Chico',
        position: 'Front-End Developer',
        promotion: 'Hopler 7',
        email: 'sabrine@gmail.com',
        phone: '+32-11-11-31-11',
        location: 'Mechlen , Belgium',
        status: 'active',
        Starting_date: '01/09/2022',
    },
    {   
        id: 2,
        photo: 'http://www.globaledico.com/wp-content/uploads/revslider/homepage4/person.png',
        name: 'David Roberto',
        position: 'Back-End Developer',
        promotion: 'Hopler 7',
        email: 'Davidooo@gmail.com',
        phone: '+32-22-42-22-21',
        location: 'Anwerpen , Belgium',
        status: 'Not active',
        Starting_date: '25/07/2022',
    },
    {
        id: 3,
        photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1HhReWThCQdCs3ZkfNGfbnsKZqobYlJWfwv_z1H5IpmkmRXz1Wh2HDb7zPVM4Bwpofag&usqp=CAU',
        name: 'Michel Anirata',
        position: 'Front-End Developer',
        promotion: 'Hopler 7',
        email: 'mirata@gmail.com',
        phone: '+32-33-33-33-36',
        location: 'Brussels , Belgium',
        status: 'active',
        Starting_date: '01/08/2022',
    },
    {
    id: 4,
    photo: 'https://lumiere-a.akamaihd.net/v1/images/ct_frozen_anna_18466_6775584b.jpeg?region=0,0,600,600',
    name: 'Sophia dionisie',
    position: 'Back-End Developer',
    promotion: 'Hopler 7',
    email: 'Anaana@gmail.com',
    phone: '+32-14-44-24-44',
    location: 'Brussels , Belgium',
    status: 'not active',
    Starting_date: '01/09/2022',
    },
    {   
        id: 5,
        photo: 'https://media.vanityfair.com/photos/57597b77e5ce54f83ee20da8/master/pass/noah-galvin-Real-ONeals-Star-Being-Gay-in-Hollywood.jpg',
        name: 'Ninoah Junke',
        position: 'Back-End Developer',
        promotion: 'Hopler 7',
        email: 'nino@gmail.com',
        phone: '+32-11-11-11-11',
        location: 'Brussels , Belgium',
        status: 'active',
        Starting_date: '01/08/2022',
    },
    {   
        id: 6,
        photo: 'https://www.maxpixel.net/static/photo/1x/Girl-Face-Women-Person-Woman-Portrait-Female-6309466.jpg',
        name: 'Sandra Mariana',
        position: 'Front-End Developer',
        promotion: 'Hopler 7',
        email: 'sandy@gmail.com',
        phone: '+32-22-22-22-22',
        location: 'Brussels , Belgium',
        status: 'active',
        Starting_date: '25/07/2022',
    },
    {
        id: 7,
        photo: 'https://cdn.dnaindia.com/sites/default/files/styles/full/public/2021/05/25/975670-961858-r3.jpg',
        name: 'Alberto Saintiano',
        position: 'Front-End Developer',
        promotion: 'Hopler 7',
        email: 'albert@gmail.com',
        phone: '+32-33-33-33-33',
        location: 'Brussels , Belgium',
        status: 'active',
        Starting_date: '01/08/2022',
    },
    {
    id: 8,
    photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgfTvKmQZl3ojuF0C4gijNXjYZPGvmmpsxSg&usqp=CAU',
    name: 'Samuelle Marker',
    position: 'Front-End Developer',
    promotion: 'Hopler 7',
    email: 'marker@gmail.com',
    phone: '+32-44-44-44-44',
    location: 'Brussels , Belgium',
    status: 'active',
    Starting_date: '01/09/2022',
    },
]


export default PromoLearnerData;